version: '3'
services:
  webserver:
    build:
      context: webserver
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - database
  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - C:/Users/SomeDude/dockerbyexample/Exercise1/db:/var/lib/mysql
    #      - ./db:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD: example_password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db: