services:
- docker
script:
- make
- ls -la | grep pdf
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: presentation.pdf
  skip_cleanup: true
  on:
    repo: uniba-ktr/PresTeX
    tags: true
