version: '3'
services:
  proxy:
    image: nginx
    volumes:
      - C:/Users/SomeDude/dockerbyexample/dockercompose/Exercise2/proxy/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - webserver
    networks:
      - php_network
  webserver:
    build:
      context: webserver
      dockerfile: Dockerfile
    depends_on:
      - database
    networks:
      - php_network
      - database_network
  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - database_v:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example_password
    networks:
      - database_network
  adminer:
    image: adminer
    restart: always
    networks:
      - database_network

volumes:
  database_v:

networks:
  database_network:

  php_network:
